server:
  port: 8091

app:
  key: AQ.Ab8RN6LfZ9u7xNtGmUWx3UPU-QMd8h6htktebszdy4up8v2KlA 
  aimodel: gemini-3.1-flash-lite
  url: https://generativelanguage.googleapis.com/v1beta/openai/
  files:
    inbound: ./data/inbound
    procesados: ./data/inbound/procesados

spring:
  docker:
    compose:
      enabled: false
      file: docker-compose.yml
  ai:
    model:
      embedding: openai
    vectorstore:
      qdrant:
        collection-name: springai_advisor
    openai:
      # Ahora esto tomará correctamente los valores del bloque "app"
      api-key: ${app.key}
      base-url: ${app.url}
      chat:
        model: ${app.aimodel}

advisor:
  memory:
    collection-name: springai_memory
    top-k: 4
  rag:
    top-k: 15
  summarization:
    enabled: false
    max-tokens: 200
    threads: 1

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
    com.programacion.taller3: DEBUG