server:
  port: 8091

app:
  key: AIzaSyDhNnQhY_UaTcplOlHaRjekm1tyTAAzIxY
  aimodel: gemini-3.1-flash-lite
  url: https://generativelanguage.googleapis.com/v1beta/openai/
  files:
    inbound: ./12.spring-advisor/data/inbound
    procesados: ./12.spring-advisor/data/inbound/tesis/procesados

spring:
  docker:
    compose:
      enabled: false
      file: docker-compose.yml
  ai:
    model:
      embedding: transformers
    embedding:
      transformer:
        onnx:
          model-uri: classpath:models/model.onnx
        tokenizer:
          uri: classpath:models/tokenizer.json
    vectorstore:
      qdrant:
        collection-name: springai_advisor
    openai:
      # Ahora esto tomará correctamente los valores del bloque "app"
      api-key: ${app.key}
      base-url: ${app.url}
      chat:
        model: ${app.aimodel}

advisor:
  thesis:
    collection-name: springai_thesis
  memory:
    collection-name: springai_memory
    top-k: 4
  rag:
    top-k: 15
  summarization:
    enabled: false
    max-tokens: 200
    threads: 1

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
    com.programacion.taller3: DEBUG